DROP TABLE IF EXISTS quiz;
CREATE TABLE quiz (
    id INT AUTO_INCREMENT PRIMARY KEY,
    continuar VARCHAR(10) NOT NULL,
    faculdade VARCHAR(10) NOT NULL,
    curso VARCHAR(10) NOT NULL,
    parar VARCHAR(10) NOT NULL,
    melhor VARCHAR(50) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
